// Fill out your copyright notice in the Description page of Project Settings.


#include "FeatureLayerQuery.h"

AFeatureLayerQuery::AFeatureLayerQuery()
{
	PrimaryActorTick.bCanEverTick = true;
}

void AFeatureLayerQuery::BeginPlay()
{
	Super::BeginPlay();

	ProcessRequest();
}

void AFeatureLayerQuery::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

void AFeatureLayerQuery::OnResponseReceived(FHttpRequestPtr Request, FHttpResponsePtr Response, bool bSuccessfullyConnected)
{
	if (!bSuccessfullyConnected)
	{
		return;
	}

	TSharedPtr<FJsonObject> responseObject;
	const auto ResponseBody = Response->GetContentAsString();
	auto Reader = TJsonReaderFactory<>::Create(ResponseBody);
	
	if (FJsonSerializer::Deserialize(Reader, responseObject))
	{
		auto featureObjects = responseObject->GetArrayField(TEXT("features"));

		for (auto feature : featureObjects)
		{
			FProperties currentFeature;
			auto coordinates = feature->AsObject()->GetObjectField(TEXT("geometry"))->GetArrayField(TEXT("coordinates"));
			auto name = feature->AsObject()->GetObjectField(TEXT("properties"))->GetStringField("Name");
			auto location = feature->AsObject()->GetObjectField(TEXT("properties"))->GetStringField("location");
			auto altitude = feature->AsObject()->GetObjectField(TEXT("properties"))->GetIntegerField("altitude");
			auto length = feature->AsObject()->GetObjectField(TEXT("properties"))->GetIntegerField("length");

			currentFeature.name = name;
			currentFeature.altitude = altitude;
			currentFeature.location = location;
			currentFeature.length = length;

			for (int i = 0; i < coordinates.Num(); i++)
			{
				auto thisGeometry = coordinates[i]->AsArray();
				FGeometries geometry;
				geometry.geometry.Add(thisGeometry[0]->AsNumber());
				geometry.geometry.Add(thisGeometry[1]->AsNumber());
				currentFeature.geometries.Add(geometry);
			}
			
			features.Add(currentFeature);
		}
	}
}

void AFeatureLayerQuery::ProcessRequest()
{
	FHttpRequestRef Request = FHttpModule::Get().CreateRequest();
	Request->OnProcessRequestComplete().BindUObject(this, &AFeatureLayerQuery::OnResponseReceived);
	Request->SetURL(weblink);
	Request->SetVerb("Get");
	Request->ProcessRequest();
}
